### ISSUE TITLE
How do I run this network with my own data?

### ISSUE THREAD

**Issue by mostafa501** [Haiyang-W/RBGNet#4]
Dear all, thank you for publishing this work.
I am curious how to use this network on my own data. For example, say I have a PCD for chairs, I do not have the ground truth for this. I just want to run inference script to give me a list of detected objects.
How would be the best way to progress using your network? Any help on this would be very much appreciated.
Thank you for the contribution !!

**Comment by LIUXIN4558** [comment]
May I ask if you have successfully reproduced this code? I am currently experiencing this issue when reproducing it using the runrgbd dataset:
__**2024-07-25 16:03:37,464   INFO  Loading SUNRGBD dataset
Traceback (most recent call last):
  File "train.py", line 204, in <module>
    main()
  File "train.py", line 105, in main
    train_set, train_loader, train_sampler = build_dataloader(
  File "/home/ipsg2/code/lx2/RBGNet/tools/../pcdet/datasets/__init__.py", line 54, in build_dataloader
    dataset = __all__[dataset_cfg.DATASET](
  File "/home/ipsg2/code/lx2/RBGNet/tools/../pcdet/datasets/sunrgbd/sunrgbd_dataset.py", line 29, in __init__
    self.include_sunrgbd_data(self.mode)
  File "/home/ipsg2/code/lx2/RBGNet/tools/../pcdet/datasets/sunrgbd/sunrgbd_dataset.py", line 51, in include_sunrgbd_data
    sample_id_list.extend([info['point_cloud']['lidar_idx'] for info in infos])
  File "/home/ipsg2/code/lx2/RBGNet/tools/../pcdet/datasets/sunrgbd/sunrgbd_dataset.py", line 51, in <listcomp>
    sample_id_list.extend([info['point_cloud']['lidar_idx'] for info in infos])
TypeError: string indices must be integers_**_
I have checked the. pkl file and it does not contain 'point_cloud' and 'lidar idx'
May I ask if you have encountered such a problem?

**Comment by Haiyang-W** [comment]
Sorry for the late reply. Please refer to [here](https://github.com/Haiyang-W/CAGroup3D?tab=readme-ov-file#data-preparation) for generating your own dataset. Note that the coordinate system adopted in MMdetection3D(0.15) is very different from MMdetection3D(>=1.0).
